CREATE TABLE IF NOT EXISTS sessions (
  id                CHAR(36)     NOT NULL DEFAULT (UUID()),
  patient_id        CHAR(36)     NOT NULL,
  doctor_id         CHAR(36)     NOT NULL,
  therapy_id        CHAR(36)     NOT NULL,
  date              DATE         NOT NULL,
  time              VARCHAR(5)   NOT NULL,
  duration          INT          NOT NULL DEFAULT 60,
  status            ENUM('scheduled','completed','cancelled','rescheduled') NOT NULL DEFAULT 'scheduled',
  notes             TEXT,
  clinical_notes    TEXT,
  reschedule_count  INT          NOT NULL DEFAULT 0,
  completed_at      DATETIME,
  cancelled_at      DATETIME,
  cancel_reason     VARCHAR(300),
  created_at        DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at        DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT fk_sessions_patient  FOREIGN KEY (patient_id)  REFERENCES users(id)     ON DELETE CASCADE,
  CONSTRAINT fk_sessions_doctor   FOREIGN KEY (doctor_id)   REFERENCES users(id)     ON DELETE CASCADE,
  CONSTRAINT fk_sessions_therapy  FOREIGN KEY (therapy_id)  REFERENCES therapies(id) ON DELETE RESTRICT,
  KEY idx_sessions_patient (patient_id),
  KEY idx_sessions_doctor  (doctor_id),
  KEY idx_sessions_date    (date),
  KEY idx_sessions_status  (status),
  KEY idx_sessions_date_doctor (doctor_id, date, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
