CREATE TABLE IF NOT EXISTS products (
  id          CHAR(36)      NOT NULL DEFAULT (UUID()),
  doctor_id   CHAR(36)      NOT NULL,
  name        VARCHAR(150)  NOT NULL,
  category    VARCHAR(60)   NOT NULL,
  price       DECIMAL(10,2) NOT NULL,
  mrp         DECIMAL(10,2) NOT NULL,
  stock       INT           NOT NULL DEFAULT 0,
  unit        VARCHAR(40),
  emoji       VARCHAR(8)    NOT NULL DEFAULT '🌿',
  description TEXT,
  tags        JSON          NOT NULL DEFAULT (JSON_ARRAY()),
  dosha       JSON          NOT NULL DEFAULT (JSON_ARRAY()),
  recommended TINYINT(1)    NOT NULL DEFAULT 0,
  is_new      TINYINT(1)    NOT NULL DEFAULT 0,
  is_active   TINYINT(1)    NOT NULL DEFAULT 1,
  created_at  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT fk_products_doctor FOREIGN KEY (doctor_id) REFERENCES users(id) ON DELETE CASCADE,
  KEY idx_products_doctor    (doctor_id),
  KEY idx_products_category  (category),
  KEY idx_products_active    (is_active),
  KEY idx_products_stock     (stock)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
